version: '3'
services:
    #MariaDB
    mysql:
        image: mariadb:latest
        container_name: mysql
        volumes:
            - $HOME/website.sql:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: website
            MYSQL_USER: web
            MYSQL_PPASSWORD: 0dWK9fp%wgFN
        ports:
            - "3306:3306"
        networks:
            - app-network


    #PHP-FPM
    myphp:
        depends_on: mysql
        dockerfile: dockerfile
        volumes:
            - $HOME:/var/www/html
        container_name: myphp
        privileged: true
        restart: always
        ports:
            - "9000:9000"
        networks:
            - app-network

    #Nginx
    mynginx:
        depends_on: myphp        
        image: nginx
        volumes:
            - $HOME:/var/www/html
            - $HOME/nginx.ini:/etc/nginx/conf.d/default.conf 
            - $HOME/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
            - $HOME/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
        privileged: true
        container_name: mynginx
        restart: always
        ports:
            - "8080:80"
        networks:
            - -app-network

#Volumes
volumes: 
    database: {}

#Network
networks:
    app-network:
        driver: bridge


    






    