FROM mariadb:latest as builder


RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

# needed for intialization
ENV MYSQL_ROOT_PASSWORD=MyDBRoot123
ENV MYSQL_DATABASE: website
ENV MYSQL_USER: web
ENV MYSQL_PPASSWORD: 0dWK9fp%wgFN

COPY ./website.sql /docker-entrypoint-initdb.d/

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db", "--aria-log-dir-path", "/initialized-db"]

FROM mariadb:latest

COPY --from=builder /initialized-db /var/lib/mysql