version: '3'
services:
    #MariaDB
    mysql:
        image: mariadb:latest
        container_name: mysql
        volumes:            
            - ./sql/:/docker-entrypoint-initdb.d/
            - database:/var/lib/mysql/
        restart: always
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: website
            MYSQL_USER: web
            MYSQL_PASSWORD: 0dWK9fp%wgFN
        ports:
            - "3306:3306"
        networks:
            - app-network

    #Nginx
    mynginx:
        image: nginx:latest
        depends_on: 
            - php
            - mysql
        links:
            - php
            - mysql
        volumes:
            - ./sitepages/:/var/www/html/
            - ./nginx/:/etc/nginx/conf.d/
            - ./phpconf/:/etc/php/7.4/fpm/
            - ./wwwconf/:/etc/php/7.4/fpm/pool.d/
        privileged: true
        container_name: mynginx
        restart: always
        ports:
            - "80:80"        
        networks:
            - app-network

    #Php
    php:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./sitepages/:/var/www/html/
        container_name: myphp
        restart: always
        ports:
            - "9000:9000"
        networks:
            - app-network

    #admin for db use
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        depends_on: 
            - mysql
        links:
            - mysql
        privileged: true
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
        networks:
            - app-network

#Volumes
volumes: 
    database: 

#Network
networks:
    app-network:
        driver: bridge


    






    