version: '3'
services:
    #MariaDB
    mysql:
        image: mariadb:latest
        container_name: mysql
        volumes:
            - database:/var/lib/mysql
            - ./sql/:/docker-entrypoint-initdb.d/
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: website
            MYSQL_USER: web
            MYSQL_PPASSWORD: 0dWK9fp%wgFN
        ports:
            - "3306:3306"
        networks:
            - app-network

    #Nginx
    mynginx:
        image: nginx:latest
        depends_on: 
            - php
            - mysql
        links:
            - php
            - mysql
        volumes:
            - ./sitepages/:/var/www/html/
            - ./nginx/:/etc/nginx/conf.d/
            - ./phpconf/:/etc/php/7.4/fpm/
            - ./wwwconf/:/etc/php/7.4/fpm/pool.d/
        privileged: true
        container_name: mynginx
        restart: always
        ports:
            - "80:80"        
        networks:
            - app-network

    #Php
    php:
        image: php:7.2-fpm
        volumes:
            - ./sitepages/:/var/www/html/
            - ./phpconf/:/etc/php/7.4/fpm/
            - ./wwwconf/:/etc/php/7.4/fpm/pool.d/
            - ./phpini/:/usr/local/etc/php/
        container_name: myphp
        restart: always
        ports:
            - "9000:9000"
        networks:
            - app-network

#Volumes
volumes: 
    database: {}

#Network
networks:
    app-network:
        driver: bridge


    






    