version: '3'
services:
    #MariaDB
    mysql:
        image: mariadb:latest
        container_name: mysql
        volumes:
            - database:/var/lib/mysql
            - ./website.sql:/docker-entrypoint-initdb.d/website.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: website
            MYSQL_USER: web
            MYSQL_PPASSWORD: 0dWK9fp%wgFN
        ports:
            - "3306:3306"
        networks:
            - app-network


    #PHP-FPM
    myphp:
        depends_on: 
            - mysql
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/var/www/html
        container_name: myphp
        privileged: true
        restart: always
        ports:
            - "9000:9000"
        networks:
            - app-network

    #Nginx
    mynginx:
        depends_on: 
            - myphp        
        image: nginx
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/
            - ./php-fpm.conf:/etc/php/7.4/fpm/
            - ./www.conf:/etc/php/7.4/fpm/pool.d/
        privileged: true
        container_name: mynginx
        restart: always
        ports:
            - "80:80"
        networks:
            - app-network

#Volumes
volumes: 
    database: {}

#Network
networks:
    app-network:
        driver: bridge


    






    